### ISSUE TITLE
我在运行demo.py，用您提供的模型时，出现错误

### ISSUE THREAD

**Issue by LoeWHJ** [FLming/CRNN.tf2#10]
raise ValueError('Unknown ' + printable_module_name + ': ' + class_name)
ValueError: Unknown layer: Functional

**Comment by FLming** [comment]
什么时候下的模型？代码是最新的吗？希望提供更具体的错误信息。

**Comment by FLming** [comment]
什么版本的TF？请提供具体点的信息

**Comment by LoeWHJ** [comment]
今天下载的您的代码和提供的模型，我的tf时2.2.0的
错误提示是：
(py36) D:\whj\projects\OCR\CRNN.tf2-master&gt;python crnn/demo.py -i ./example/images/ -t D:/whj/projects/OCR/CRNN.tf2-master/example/table.txt -m ./model/exported_model.h5
2020-11-03 11:17:38.872236: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-11-03 11:17:38.875483: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
&nbsp; File "crnn/demo.py", line 41, in <module&gt;
&nbsp; &nbsp; model = keras.models.load_model(args.model, compile=False)
&nbsp; File "D:\Program Files (x86)\anaconda3\envs\py36\lib\site-packages\tensorflow\python\keras\saving\save.py", line 184, in load_model
&nbsp; &nbsp; return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
&nbsp; File "D:\Program Files (x86)\anaconda3\envs\py36\lib\site-packages\tensorflow\python\keras\saving\hdf5_format.py", line 178, in load_model_from_hdf5
&nbsp; &nbsp; custom_objects=custom_objects)
&nbsp; File "D:\Program Files (x86)\anaconda3\envs\py36\lib\site-packages\tensorflow\python\keras\saving\model_config.py", line 55, in model_from_config
&nbsp; &nbsp; return deserialize(config, custom_objects=custom_objects)
&nbsp; File "D:\Program Files (x86)\anaconda3\envs\py36\lib\site-packages\tensorflow\python\keras\layers\serialization.py", line 109, in deserialize
&nbsp; &nbsp; printable_module_name='layer')
&nbsp; File "D:\Program Files (x86)\anaconda3\envs\py36\lib\site-packages\tensorflow\python\keras\utils\generic_utils.py", line 373, in deserialize_keras_object
&nbsp; &nbsp; list(custom_objects.items())))
&nbsp; File "D:\Program Files (x86)\anaconda3\envs\py36\lib\site-packages\tensorflow\python\keras\engine\sequential.py", line 398, in from_config
&nbsp; &nbsp; custom_objects=custom_objects)
&nbsp; File "D:\Program Files (x86)\anaconda3\envs\py36\lib\site-packages\tensorflow\python\keras\layers\serialization.py", line 109, in deserialize
&nbsp; &nbsp; printable_module_name='layer')
&nbsp; File "D:\Program Files (x86)\anaconda3\envs\py36\lib\site-packages\tensorflow\python\keras\utils\generic_utils.py", line 362, in deserialize_keras_object
&nbsp; &nbsp; config, module_objects, custom_objects, printable_module_name)
&nbsp; File "D:\Program Files (x86)\anaconda3\envs\py36\lib\site-packages\tensorflow\python\keras\utils\generic_utils.py", line 321, in class_and_config_for_serialized_keras_object
&nbsp; &nbsp; raise ValueError('Unknown ' + printable_module_name + ': ' + class_name)
ValueError: Unknown layer: Functional







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "FLming/CRNN.tf2"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月3日(星期二) 中午11:33
收件人:&nbsp;"FLming/CRNN.tf2"<CRNN.tf2@noreply.github.com&gt;;
抄送:&nbsp;"🔥"<2642264392@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [FLming/CRNN.tf2] 我在运行demo.py，用您提供的模型时，出现错误 (#10)





 
什么版本的TF？请提供具体点的信息

**Comment by FLming** [comment]
具体原因是有眉毛的，tf2.3是能工作的，我给的模型是在导出时加了一层softmax的。2.2居然不支持functional层的加载吗？我稍后验证一下。


------------------ 原始邮件 ------------------
发件人: LoeWHJ <notifications@github.com&gt;
发送时间: 2020年11月3日 11:36
收件人: FLming/CRNN.tf2 <CRNN.tf2@noreply.github.com&gt;
抄送: Yiming Huang <yiminghd@foxmail.com&gt;, Assign <assign@noreply.github.com&gt;
主题: 回复：[FLming/CRNN.tf2] 我在运行demo.py，用您提供的模型时，出现错误 (#10)





 今天下载的您的代码和提供的模型，我的tf时2.2.0的 
 错误提示是： 
 (py36) D:\whj\projects\OCR\CRNN.tf2-master&amp;gt;python crnn/demo.py -i ./example/images/ -t D:/whj/projects/OCR/CRNN.tf2-master/example/table.txt -m ./model/exported_model.h5 
 2020-11-03 11:17:38.872236: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found 
 2020-11-03 11:17:38.875483: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine. 
 Traceback (most recent call last): 
 &amp;nbsp; File "crnn/demo.py", line 41, in <module&amp;gt; 
 &amp;nbsp; &amp;nbsp; model = keras.models.load_model(args.model, compile=False) 
 &amp;nbsp; File "D:\Program Files (x86)\anaconda3\envs\py36\lib\site-packages\tensorflow\python\keras\saving\save.py", line 184, in load_model 
 &amp;nbsp; &amp;nbsp; return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile) 
 &amp;nbsp; File "D:\Program Files (x86)\anaconda3\envs\py36\lib\site-packages\tensorflow\python\keras\saving\hdf5_format.py", line 178, in load_model_from_hdf5 
 &amp;nbsp; &amp;nbsp; custom_objects=custom_objects) 
 &amp;nbsp; File "D:\Program Files (x86)\anaconda3\envs\py36\lib\site-packages\tensorflow\python\keras\saving\model_config.py", line 55, in model_from_config 
 &amp;nbsp; &amp;nbsp; return deserialize(config, custom_objects=custom_objects) 
 &amp;nbsp; File "D:\Program Files (x86)\anaconda3\envs\py36\lib\site-packages\tensorflow\python\keras\layers\serialization.py", line 109, in deserialize 
 &amp;nbsp; &amp;nbsp; printable_module_name='layer') 
 &amp;nbsp; File "D:\Program Files (x86)\anaconda3\envs\py36\lib\site-packages\tensorflow\python\keras\utils\generic_utils.py", line 373, in deserialize_keras_object 
 &amp;nbsp; &amp;nbsp; list(custom_objects.items()))) 
 &amp;nbsp; File "D:\Program Files (x86)\anaconda3\envs\py36\lib\site-packages\tensorflow\python\keras\engine\sequential.py", line 398, in from_config 
 &amp;nbsp; &amp;nbsp; custom_objects=custom_objects) 
 &amp;nbsp; File "D:\Program Files (x86)\anaconda3\envs\py36\lib\site-packages\tensorflow\python\keras\layers\serialization.py", line 109, in deserialize 
 &amp;nbsp; &amp;nbsp; printable_module_name='layer') 
 &amp;nbsp; File "D:\Program Files (x86)\anaconda3\envs\py36\lib\site-packages\tensorflow\python\keras\utils\generic_utils.py", line 362, in deserialize_keras_object 
 &amp;nbsp; &amp;nbsp; config, module_objects, custom_objects, printable_module_name) 
 &amp;nbsp; File "D:\Program Files (x86)\anaconda3\envs\py36\lib\site-packages\tensorflow\python\keras\utils\generic_utils.py", line 321, in class_and_config_for_serialized_keras_object 
 &amp;nbsp; &amp;nbsp; raise ValueError('Unknown ' + printable_module_name + ': ' + class_name) 
 ValueError: Unknown layer: Functional 
 
 
 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "FLming/CRNN.tf2"                                                                                    <notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年11月3日(星期二) 中午11:33 
 收件人:&amp;nbsp;"FLming/CRNN.tf2"<CRNN.tf2@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"🔥"<2642264392@qq.com&amp;gt;;"Author"<author@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [FLming/CRNN.tf2] 我在运行demo.py，用您提供的模型时，出现错误 (#10) 
 
 
 
 
 
   
 什么版本的TF？请提供具体点的信息

**Comment by FLming** [comment]
问题已复现。

**Comment by FLming** [comment]
相关[问题](https://stackoverflow.com/questions/63068639/valueerror-unknown-layer-functional)，确认使用functional建立的h5模型无法在2.2被加载，SavedModel格式是可行的。但迁移学习时，SavedModel还是不够方便。所以可能的话，请更新TensorFlow到2.3以上。2.2中部分功能依旧可以使用，只是导出模型时需要使用SavedModel使加载功能能够工作，或者通过代码构建模型以使h5权重能够正常加载。

Tensorflow 2.3 Changelog:
```
Functional models now get constructed if any tensor in a layer call's arguments/keyword arguments comes from a keras input. 
Previously the functional api would only work if all of the elements in the first argument to the layer came from a keras input.
```

**Comment by FLming** [comment]
确认2.3下导出的SavedModel格式模型，依旧无法在2.2版本下工作。:sweat_smile:

**Comment by LoeWHJ** [comment]
把tf 升级到了2.3可以用了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "FLming/CRNN.tf2"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月3日(星期二) 中午1:09
收件人:&nbsp;"FLming/CRNN.tf2"<CRNN.tf2@noreply.github.com&gt;;
抄送:&nbsp;"🔥"<2642264392@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [FLming/CRNN.tf2] 我在运行demo.py，用您提供的模型时，出现错误 (#10)





 
确认2.3下导出的SavedModel格式模型，依旧无法在2.2版本下工作。😅
