### ISSUE TITLE
Getting Nan loss on MJSynth Dataset

### ISSUE THREAD

**Issue by YunusAbdi** [FLming/CRNN.tf2#16]
I downloaded the MJSynth dataset and followed the instructions but while training at the first epoch the loss suddenly changes to Nan, i tried adding regularization and norm clipping but both didn't fix the problem

Also the sequence accuracy is 0.0 most of the time

**Comment by daeing** [comment]
> I downloaded the MJSynth dataset and followed the instructions but while training at the first epoch the loss suddenly changes to Nan, i tried adding regularization and norm clipping but both didn't fix the problem
> 
> Also the sequence accuracy is 0.0 most of the time

Hello, I met the same problem. Did you solve it?

**Comment by FLming** [comment]
Please provide more information. 
By the way, here is a [log](https://tensorboard.dev/experiment/00E6pePZTjWA3H3CMS8LdA/) trained by the MJSynth dataset.

**Comment by ddddddreamcastle** [comment]
I met the same problem. The sequence_accuracy is always 0.0, but the loss looks like going down normally.

**Comment by FLming** [comment]
Don't worry. it's normal. please continue your training.
