### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa6 in position 363: illegal multibyte sequence

### ISSUE THREAD

**Issue by AoligeiFowever** [FLming/CRNN.tf2#19]
![image](https://user-images.githubusercontent.com/57721325/120920385-08ae7100-c6f1-11eb-8c18-82aa9aab41f9.png)
您好，请问这个编码报错是怎么回事呢

**Comment by AoligeiFowever** [comment]
![image](https://user-images.githubusercontent.com/57721325/120920473-8e322100-c6f1-11eb-8c6b-363a55edb03f.png)
我的train_ann_paths是这样的，请问是哪里不合规范吗

**Comment by FLming** [comment]
没有问题，你是读不到图片还是？文本文件中记录的是相对位置

**Comment by AoligeiFowever** [comment]
> 没有问题，你是读不到图片还是？文本文件中记录的是相对位置
> […](#)
> 在 2021年6月6日，下午6:04，AoligeiFowever ***@***.***> 写道： ﻿ 我的train_ann_paths是这样的，请问是哪里不合规范吗 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

与其说我读不到图片，实际上好像是不能正确读取这个yml配置文件呢，在读取配置文件的那部分报错说gbk编码问题，而我的注释文件格式应该是没有问题的，确认过是utf8编码，而且我在colab上成功运行过

**Comment by FLming** [comment]
那可能是python文件的编码问题，这个你得自己确认一下了。

**Comment by FLming** [comment]
> ![image](https://user-images.githubusercontent.com/57721325/120920385-08ae7100-c6f1-11eb-8c18-82aa9aab41f9.png)
> 您好，请问这个编码报错是怎么回事呢

之前没看到这个图片，预计是你的python解释器和你的注释文件使用的不是一个编码导致的。
