### ISSUE TITLE
Bug:tensorflow/core/util/ctc/ctc_loss_calculator.cc:145] No valid path found.

### ISSUE THREAD

**Issue by SimonWang00** [FLming/CRNN.tf2#2]
@FLming 感谢作者的分享，我在运行时发现，输入的标签较长时，会有如下报错，请问如何调整，谢谢！

tensorflow/core/util/ctc/ctc_loss_calculator.cc:144] No valid path found.

**Comment by FLming** [comment]
网络输出序列长度的话，是网络下采样和图片宽度共同决定的。举个例子，图片宽度是100，网络共下采样4次加一个核为2的卷积，最后序列长24，因此最后的ctc不允许序列长度大于24的标签。

因为我没尝试过输入超过这个限制的长度，单看这个错误提示的话，也没明确指出是这个问题。希望能帮到你。

**Comment by SimonWang00** [comment]
@FLming 感谢你的解答，我想我知道原因在哪里了。所以我只需要调整输入图片的宽度，就可以达到增加序列长的目的，我一会尝试下。

**Comment by SimonWang00** [comment]
@FLming 问题已解决，多谢！
