### ISSUE TITLE
Ragged Tensors in Keras

### ISSUE THREAD

**Issue by thetruejacob** [FLming/CRNN.tf2#26]
Thank you so much for this incredibly useful repo. I see in dataset_factory.py that you are waiting for RaggedTensor support in Keras. But isn't this already available?

https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/guide/ragged_tensor.ipynb

Is there any plan to implement this at some point?

**Comment by FLming** [comment]
In the early days, I simply tested it and found that it did not bring performance improvement.

**Comment by thetruejacob** [comment]
Got it. Was it much worse? Thanks very much again.

**Comment by FLming** [comment]
I don’t remember the specific data. In my previous test, using ragged is slower than sparse, probably because ctc use SparseTensor also has a good implementation on cpu.
