### ISSUE TITLE
Is 'Sequence Accuracy' referring only to exact matches?

### ISSUE THREAD

**Issue by thetruejacob** [FLming/CRNN.tf2#27]
If I'm understanding correctly, the metric of 'sequence accuracy', for example val_sequence_accuracy: 0.52 means that 52% of each image in the validation set is read perfectly. Is there a way to ignore differences in spaces? I'm trying to read entire lines of images at once, and would like the prediction of 'hello there' to be considered equivalent to 'hello     there' (even if the CTCLoss will be different, sequence_accuracy should be considered the same).

**Comment by FLming** [comment]
Yes, the current statistical method is a complete match, you can modify the calculation method(update_state function) yourself.

**Comment by thetruejacob** [comment]
Thanks very much.

**Comment by thetruejacob** [comment]
Sorry, but can you point me to where exactly I can make this change? If I'm understanding correctly, it's in metrics.py specifically lines 27 and 28 which are:

 y_true = sparse2dense(y_true, [batch_size, max_width])
 y_pred = sparse2dense(decoded[0], [batch_size, max_width])

but these are tensors that are converted from sparse to dense. For me, the 'space' character is the 2nd label in the table of characters. Does that mean I have to tell it to ignore differences in the 2nd characters somehow? 

Or is there a way to access the predicted values without tensors (but I think that would make it slower?)

**Comment by FLming** [comment]
Sorry, I didn't notice the email. In the function, the conversion to densor tensor is only because the compared api does not support sparse tensor. You can think about how to count whether it matches or not. The simplest, circular comparison, ignoring spaces is a crude implementation.
