### ISSUE TITLE
predict not True

### ISSUE THREAD

**Issue by duongngocthien** [FLming/CRNN.tf2#29]
![image](https://user-images.githubusercontent.com/75648675/145729112-fe928551-ae6e-44f0-a7fe-aa416d7ed432.png)

I use the demo file to predict, the config file is like below.
dataset_builder: &ds_builder
    table_path: 'example/table.txt'
    img_shape: [32, null, 3]
    max_img_width: 400
    ignore_case: true

train:
    dataset_builder:
        <<: *ds_builder
    train_ann_paths:
        - '/content/gdrive/MyDrive/CRNN/CRNN.tf2/example/annotation_train.txt'
        - '/content/gdrive/MyDrive/CRNN/CRNN.tf2/example/annotation_val.txt'
    val_ann_paths:
        - '/content/gdrive/MyDrive/CRNN/CRNN.tf2/example/annotation_test.txt'
    batch_size_per_replica: 32
    # Number of epochs to train.
    epochs: 2000
    lr_schedule:
        initial_learning_rate: 0.0001
        decay_steps: 600000
        alpha: 0.01
    # TensorBoard Arguments
    # https://www.tensorflow.org/api_docs/python/tf/keras/callbacks/TensorBoard#arguments_1
    tensorboard:
        histogram_freq: 1
        profile_batch: 0

eval:
    dataset_builder:
        <<: *ds_builder
    ann_paths:
        - '/content/gdrive/MyDrive/CRNN/CRNN.tf2/example/annotation_eval.txt'
    batch_size: 1

probability: [0.9999411] , but result show is <Unk>. It only displays numbers, not characters. 
The result it returns is :
test_images/IMG_20211212_091803.jpg, y_pred: [b'<UNK><UNK><UNK>'], probability: [0.9999411] . 
While I'm looking forward to is :"HSD". 
Hope you answer.

**Comment by FLming** [comment]
Can you attach the first or second image?
