### ISSUE TITLE
您好，如何只识别数字

### ISSUE THREAD

**Issue by l976308589** [FLming/CRNN.tf2#3]
我将table.txt改成
0
1
2
3
4
5
6
7
8
9
<BLK>
运行之后显示IndexError: list index out of range

**Comment by FLming** [comment]
你是否想让提供的那个模型只识别数字？那请对解码之后的字符串做后处理，否则，请使模型的输出和table中的字符个数匹配。比如，修改table后训练一个只识别数字的模型。
