### ISSUE TITLE
Expected concatenating dimensions in the range [-1, 1), but got 1 [Op:ConcatV2] name: concat

### ISSUE THREAD

**Issue by PeiChiChen** [FLming/CRNN.tf2#37]
您好，我在執行B106Roger的CRNN.tf2 (網址：https://github.com/B106Roger/CRNN.tf2) 的eval_full_tflite.py時使用Beam Search Decoder並出現下列錯誤
tensorflow.python.framework.errors_impl.InvalidArgumentError: ConcatOp : Expected concatenating dimensions in the range [-1, 1), but got 1 [Op:ConcatV2] name: concat

![image](https://user-images.githubusercontent.com/88931868/186607500-b33158a3-464a-442e-b1db-06b7b1f67eeb.png)

因為該作者的code是從您這裡延伸的，而且在decoder.py的部分並沒有修改，所以想請問這樣的錯誤是否有出現過，也想請問解決辦法，感謝！

**Comment by FLming** [comment]
您那边自己检查一下？这个报错已经提示得很明显了。tf.concat部分，API中关于axis参数是这么描述的，也就是说你截图中的部分，strings参数的维度不太正确。

0-D int32 Tensor. Dimension along which to concatenate. Must be in the range [-rank(values), rank(values)). As in Python, indexing for axis is 0-based. Positive axis in the rage of [0, rank(values)) refers to axis-th dimension. And negative axis refers to axis + rank(values)-th dimension.
