### ISSUE TITLE
您好，训练过程中出现错误，希望能得到答复

### ISSUE THREAD

**Issue by G-ChasingTeenager** [FLming/CRNN.tf2#4]
系统：Windows10
python版本：3.7.7
tensorflow版本：2.2.0-gpu
情况：在训练开始后几个批次就出现Error polling for event status: failed to query event: CUDA_ERROR_LAUNCH_FAILED: unspecified launch failure

**Comment by FLming** [comment]
具体原因并不是很清楚，请参考https://github.com/tensorflow/tensorflow/issues/33536
