### ISSUE TITLE
the problem of Tibetan text recognition

### ISSUE THREAD

**Issue by xc-Cyuan** [FLming/CRNN.tf2#8]
Hi, dear, it seems that you use 'chars = tf.strings.unicode_split(labels, 'UTF-8')' to split label strings in the project, now I want using the graphemes function to split charactors of Tibetan(Tibetan characters are variable length unicode), but I get the error 'OperatorNotAllowedInGraphError: iterating over `tf.Tensor` is not allowed: AutoGraph did not convert this function. Try decorating it directly with @tf.function.' . What should I do? Or do you have any good suggestions?

**Comment by FLming** [comment]
About my first idea, maybe you can add some splittable char to you label(, or #), then use tf.string.split to split it.

**Comment by xc-Cyuan** [comment]
> About my first idea, maybe you can add some splittable char(, or #) to you label, then use tf.string.split to split it.


Ok, thank you very much! I think I know what to do, and I will rebuild the style of labels for my dataset.
